test_non_release_branches:
    image: debian:stable
    script:
    - apt-get update -q
    - apt-get install -qy python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-natsort python3-sklearn python3-dill python3-ipython-genutils python3-matplotlib python3-skimage python3-pint python3-requests python3-tqdm python3-traits python3-toolz python3-jupyter-client python3-ipython python3-ipykernel python3-markupsafe python3-bleach python3-entrypoints python3-html5lib python3-ipywidgets python3-jinja2 python3-jsonschema python3-mistune python3-nbconvert python3-nbformat python3-notebook python3-pandas python3-pandocfilters python3-patsy python3-terminado python3-testpath python3-webencodings python3-widgetsnbextension python3-pyqt5
    - apt-get install -qy python3-sympy --no-install-recommends
    - apt-get install -qy xvfb python3-pytest git
    - pip3 install nbval
    - pip3 install hyperspy[all]
    - git clone -b master --single-branch https://gitlab.com/atomap/atomap.git
    - pip3 install atomap/
    - xvfb-run -a python3 -m pytest --nbval-lax introduction_to_atomap.ipynb
    - cd nanoparticle_example_notebook
    - xvfb-run -a python3 -m pytest --nbval-lax --current-env
    - cd ../scripts
    - xvfb-run -a python3 minimal_example_perovskite_100.py
    - xvfb-run -a python3 minimal_example_perovskite_100_manual.py
    - xvfb-run -a python3 minimal_example_perovskite_110.py
    except:
    - release

test_release_branch:
    image: debian:stable
    script:
    - apt-get update -q
    - apt-get install -qy python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-natsort python3-sklearn python3-dill python3-ipython-genutils python3-matplotlib python3-skimage python3-pint python3-requests python3-tqdm python3-traits python3-toolz python3-jupyter-client python3-ipython python3-ipykernel python3-markupsafe python3-bleach python3-entrypoints python3-html5lib python3-ipywidgets python3-jinja2 python3-jsonschema python3-mistune python3-nbconvert python3-nbformat python3-notebook python3-pandas python3-pandocfilters python3-patsy python3-terminado python3-testpath python3-webencodings python3-widgetsnbextension python3-pyqt5
    - apt-get install -qy python3-sympy --no-install-recommends
    - apt-get install -qy xvfb python3-pytest git
    - pip3 install nbval
    - pip3 install hyperspy[all]
    - git clone -b release --single-branch https://gitlab.com/atomap/atomap.git
    - pip3 install atomap/
    - xvfb-run -a python3 -m pytest --nbval-lax introduction_to_atomap.ipynb
    - cd nanoparticle_example_notebook
    - xvfb-run -a python3 -m pytest --nbval-lax --current-env
    - cd ../scripts
    - xvfb-run -a python3 minimal_example_perovskite_100.py
    - xvfb-run -a python3 minimal_example_perovskite_100_manual.py
    - xvfb-run -a python3 minimal_example_perovskite_110.py
    only:
    - release
