name: Tests

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
      - name: Install conda-forge dependencies
        run: conda install pip hyperspy exspy ase pytest nbval atomap -c conda-forge -y
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Jupyter Notebooks
        run: pytest --nbval-lax introduction_to_atomap.ipynb
